### ISSUE TITLE
Annoying "Save" glitch in new Conversation Entities editor

### ISSUE THREAD

**Issue by dwakeman** [jdcalus/STSA-Workshop-2-WCS#1]
I had trouble with the `@degree` entity when I first created it.  I was able to create the `Celsius` value just fine, but when I added the `Fahrenheit` value it didn't get saved.  I didn't know that until later in the lab when I was building my dialog.   

What I learned is that when you add values to an entity, when you've entered the last one, you might have to click the plus sign at the far right to create another value, even if you don't have another one to add.  If you do that, then you can click away and it will discard that line.  If you don't do that and you click away you will lose the last line that you entered.

This is is more of proctor's note than a defect, but I suspect you'll run into it quite a bit.

**Comment by jdcalus** [comment]
I saw this recently also. I now instruct the user to hit the "Plus Sign" to make sure it is saved.
