### ISSUE TITLE
Duplicate steps in lab

### ISSUE THREAD

**Issue by dwakeman** [jdcalus/STSA-Workshop-2-WCS#2]
At first glance it looks like steps `p` and `q` are exactly the same step, both the description and the screen shot.  Is it a duplicate, or is one of them supposed to be a different step that didn't get documented?

**Comment by dwakeman** [comment]
In later testing of the lab using the web client, I noticed that when I ask it to change the color, it gives me the response that it changed the color, but did not redirect me to the "what else" node.  Is that what the duplicate entry should have told me to do?  Change the `wait for user input` at the bottom of the Color Change node to a `Jump to` the response of `What Else`?

**Comment by jdcalus** [comment]
The second one was supposed to be for "Color Change" node. I have updated the readme.md
